insert into categories (category_name)
values ('Spirits'),
('Liquers');    

insert into products (category_id,product_name,price,quantity_remaining,description,image)
values ('1','Vodka','15.99','13','Vodka is a chameleon and blends seamlessly with just about anything. This is no accident: While there are no universal rules for producing the spirit, the final product is supposed to be colorless, odorless and tasteless. With that said, vodka isn’t completely neutral, and a number of distillers actually leave in a good amount of flavor. (The best way to taste these subtle differences is to drink vodka neat at room temperature.) Traditionally, vodka was made from potatoes, corn or grains, but it is now made from a range of exotic bases including grapes, maple syrup and even soybeans. Unlike Scotches and cognacs, which are made in pot stills, vodka is usually produced in a high-volume, continuous column still. After distillation, the spirit is filtered to remove any remaining impurities. Coal is a traditional filter, but brands today use a range of materials, even including diamonds. Vodka isn’t aged and can be bottled and sold immediately after production. What’s also helping to drive sales in America is the wide range of flavored vodkas now on the market.
','vodka.jpeg'),
('1','Tequila','57.99','17','Contrary to popular belief, tequila is not cactus juice. The spirit is distilled from blue Weber agave. (And for the record, it should never come with a worm in the bottle.)
Just like Champagne or cognac, tequila can only be made in a specific region: the Mexican state of Jalisco and some surrounding areas. The area’s volcanic soil is perfect for growing agave. The forbidding plant, which has sharp thorns and long, thick leaves, takes between eight and 12 years to reach maturity before it can be harvested.
The heart of the plant, which can weigh well over 100 pounds, is peeled, roasted and crushed, and its sweet juice is then fermented and distilled. (While premium tequila is made from pure agave, cheaper tequila called mixto is distilled from both agave and other sugars.) Tequila is usually distilled twice.
There are four main tequila categories: Blanco (also called silver, plata or platinum) is aged for less than two months and is clear; reposado is aged between two and 12 months and is golden-colored; añejo is aged between one and three years and is a whisky-like brown; and extra-añejo, a new category introduced by the Tequila Regulatory Council in 2006, is aged more than three years. Tequila, like most Scotches, is typically aged in used bourbon casks.','tequila.jpeg'),
('2','Triple Sec','35.99','21','Triple sec, originally Curaçao triple sec, is a variety of Curaçao liqueur, an orange-flavoured liqueur made from the dried peels of bitter and sweet orange.

Triple sec may be consumed neat as a digestif or on the rocks, but is more likely to be used as an ingredient in a variety of cocktails such as the sangria, margarita, Kamikaze, White Lady, Long Island Iced Tea, Sidecar, Skittle Bomb, Corpse Reviver #2 and Cosmopolitan.','triplesec.jpeg'),
('2','Blue Curacao','24.99','22','Curaçao is a liqueur flavored with the dried peel of the laraha citrus fruit, grown on the island of Curaçao.

A non-native plant similar to an orange, the laraha developed from the sweet Valencia orange transplanted by Spanish explorers. The nutrient-poor soil and arid climate of Curaçao proved unsuitable to Valencia cultivation, resulting in small, bitter fruit of the trees. Although the bitter flesh of the laraha is hardly edible, the peels are aromatic and flavorful, maintaining much of the essence of the Valencia orange.

Curaçao liqueur was first developed and marketed by the Senior family in the 19th century.To create the liqueur the laraha peel is dried, bringing out the sweetly fragranced oils. After soaking in a still with alcohol and water for several days, the peel is removed and other spices are added. The liqueur has an orange-like flavor with varying degrees of bitterness. It is naturally colorless, but is often given artificial coloring, most commonly blue or orange, which confers an exotic appearance to cocktails and other mixed drinks. Blue color is achieved by adding a food colorant, most often E133 Brilliant Blue.','bluecuracao.jpeg');